//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_prosp_cont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_prosp_cont()
        {
            this.inf_prosp_seg = new HashSet<inf_prosp_seg>();
        }
    
        public System.Guid prosp_cont_ID { get; set; }
        public string dpto { get; set; }
        public string contacto { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid usuario_ID { get; set; }
        public System.Guid prospecto_ID { get; set; }
    
        public virtual inf_prospectos inf_prospectos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_prosp_seg> inf_prosp_seg { get; set; }
    }
}
