//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_clte_contacto
    {
        public System.Guid clte_contacto_ID { get; set; }
        public string dpto { get; set; }
        public string contacto_nom { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string email1 { get; set; }
        public string email2 { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid clte_ID { get; set; }
    
        public virtual inf_clte inf_clte { get; set; }
    }
}
