//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_prosp_seg
    {
        public System.Guid prosp_seg_ID { get; set; }
        public Nullable<int> prosp_taccion_ID { get; set; }
        public string comentarios { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid usuario_ID { get; set; }
        public Nullable<System.Guid> prosp_cont_ID { get; set; }
    
        public virtual fact_prosp_taccion fact_prosp_taccion { get; set; }
        public virtual inf_prosp_cont inf_prosp_cont { get; set; }
    }
}
