//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_rpc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_rpc()
        {
            this.inf_ensaye_esp = new HashSet<inf_ensaye_esp>();
        }
    
        public System.Guid concreto_rpc_ID { get; set; }
        public int concreto_est_ID { get; set; }
        public string concreto_est_muestra { get; set; }
        public Nullable<System.DateTime> fecha_colado { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string entrega { get; set; }
        public string recibe { get; set; }
        public Nullable<int> presion { get; set; }
        public int especimen_tipo_ID { get; set; }
        public int concreto_tipo_ID { get; set; }
        public int concreto_situacion_ID { get; set; }
        public string procedecia { get; set; }
        public string elemento { get; set; }
        public string dosificacion { get; set; }
        public string resistencia { get; set; }
        public Nullable<int> clase { get; set; }
        public Nullable<decimal> reva { get; set; }
        public Nullable<int> tma { get; set; }
        public string olla { get; set; }
        public string remision { get; set; }
        public Nullable<System.TimeSpan> salida_planta { get; set; }
        public Nullable<System.TimeSpan> llegada_obra { get; set; }
        public Nullable<System.TimeSpan> desca_ini { get; set; }
        public Nullable<System.TimeSpan> desca_term { get; set; }
        public Nullable<decimal> vol { get; set; }
        public Nullable<decimal> revb { get; set; }
        public string localiza { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid usuario_ID { get; set; }
        public System.Guid clte_obras_ID { get; set; }
    
        public virtual fact_concreto_est fact_concreto_est { get; set; }
        public virtual fact_concreto_situacion fact_concreto_situacion { get; set; }
        public virtual fact_concreto_tipo fact_concreto_tipo { get; set; }
        public virtual fact_especimen_tipo fact_especimen_tipo { get; set; }
        public virtual inf_clte_obras inf_clte_obras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_ensaye_esp> inf_ensaye_esp { get; set; }
    }
}
