//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_clte_obras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_clte_obras()
        {
            this.inf_clte_obra_rpt = new HashSet<inf_clte_obra_rpt>();
            this.inf_rpc = new HashSet<inf_rpc>();
        }
    
        public System.Guid clte_obras_ID { get; set; }
        public Nullable<int> est_obra_ID { get; set; }
        public string clave_obra { get; set; }
        public string desc_obra { get; set; }
        public string coordinador { get; set; }
        public string contacto_obra { get; set; }
        public int tipo_servicio_ID { get; set; }
        public string comentarios { get; set; }
        public System.Guid clte_ID { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid usuario_ID { get; set; }
    
        public virtual fact_est_obra fact_est_obra { get; set; }
        public virtual fact_tipo_servicio fact_tipo_servicio { get; set; }
        public virtual inf_clte inf_clte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_clte_obra_rpt> inf_clte_obra_rpt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_rpc> inf_rpc { get; set; }
    }
}
