//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_ensaye_esp
    {
        public System.Guid ensaye_esp_ID { get; set; }
        public string ensaye_esp_cod { get; set; }
        public Nullable<int> ensaye_esp_dia { get; set; }
        public Nullable<int> ensaye_esp_numdia { get; set; }
        public Nullable<int> ensaye_esp_num { get; set; }
        public Nullable<System.DateTime> ensaye_esp_registro { get; set; }
        public int ensaye_esp_est_ID { get; set; }
        public Nullable<int> cde { get; set; }
        public Nullable<int> cdem { get; set; }
        public Nullable<int> clave_ensa_a { get; set; }
        public Nullable<decimal> masa_a { get; set; }
        public Nullable<decimal> altura_a { get; set; }
        public Nullable<decimal> altura_b { get; set; }
        public Nullable<decimal> lados_a { get; set; }
        public Nullable<decimal> lados_b { get; set; }
        public string directo_a { get; set; }
        public string intensidad_a { get; set; }
        public Nullable<decimal> presion_a { get; set; }
        public string tipofalla_a { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid concreto_rpc_ID { get; set; }
    
        public virtual fact_ensaye_esp_est fact_ensaye_esp_est { get; set; }
        public virtual inf_rpc inf_rpc { get; set; }
    }
}
