//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_clte_obra_rpt
    {
        public System.Guid clte_obra_rpt_ID { get; set; }
        public Nullable<int> est_clte_obra_rpt_ID { get; set; }
        public string nombre_archivo { get; set; }
        public string ruta_archivo { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid usuario_ID { get; set; }
        public System.Guid clte_obras_ID { get; set; }
    
        public virtual fact_est_clte_obra_rpt fact_est_clte_obra_rpt { get; set; }
        public virtual inf_clte_obras inf_clte_obras { get; set; }
    }
}
