//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_ensaye_esp
    {
        public System.Guid ensaye_esp_ID { get; set; }
        public string ensaye_esp_cod { get; set; }
        public Nullable<int> ensaye_esp_dia { get; set; }
        public Nullable<int> ensaye_esp_numdia { get; set; }
        public Nullable<int> ensaye_esp_num { get; set; }
        public Nullable<System.DateTime> ensaye_esp_registro { get; set; }
        public int ensaye_esp_est_ID { get; set; }
        public Nullable<int> cde { get; set; }
        public Nullable<int> cdem { get; set; }
        public Nullable<int> clave_ensa_a_uno { get; set; }
        public Nullable<decimal> masa_a_uno { get; set; }
        public Nullable<decimal> altura_aa_uno { get; set; }
        public Nullable<decimal> altura_ab_uno { get; set; }
        public Nullable<decimal> lados_aa_uno { get; set; }
        public Nullable<decimal> lados_ab_uno { get; set; }
        public string directo_a_uno { get; set; }
        public string intensidad_a_uno { get; set; }
        public Nullable<decimal> presion_a_uno { get; set; }
        public string tipofalla_a_uno { get; set; }
        public Nullable<int> clave_ensa_b_uno { get; set; }
        public Nullable<decimal> masa_b_uno { get; set; }
        public Nullable<decimal> altura_ba_uno { get; set; }
        public Nullable<decimal> altura_bb_uno { get; set; }
        public Nullable<decimal> lados_ba_uno { get; set; }
        public Nullable<decimal> lados_bb_uno { get; set; }
        public string directo_b_uno { get; set; }
        public string intensidad_b_uno { get; set; }
        public Nullable<decimal> presion_b_uno { get; set; }
        public string tipofalla_b_uno { get; set; }
        public Nullable<int> clave_ensa_a_tres { get; set; }
        public Nullable<decimal> masa_a_tres { get; set; }
        public Nullable<decimal> altura_aa_tres { get; set; }
        public Nullable<decimal> altura_ab_tres { get; set; }
        public Nullable<decimal> lados_aa_tres { get; set; }
        public Nullable<decimal> lados_ab_tres { get; set; }
        public string directo_a_tres { get; set; }
        public string intensidad_a_tres { get; set; }
        public Nullable<decimal> presion_a_tres { get; set; }
        public string tipofalla_a_tres { get; set; }
        public Nullable<int> clave_ensa_b_tres { get; set; }
        public Nullable<decimal> masa_b_tres { get; set; }
        public Nullable<decimal> altura_ba_tres { get; set; }
        public Nullable<decimal> altura_bb_tres { get; set; }
        public Nullable<decimal> lados_ba_tres { get; set; }
        public Nullable<decimal> lados_bb_tres { get; set; }
        public string directo_b_tres { get; set; }
        public string intensidad_b_tres { get; set; }
        public Nullable<decimal> presion_b_tres { get; set; }
        public string tipofalla_b_tres { get; set; }
        public Nullable<int> clave_ensa_a_siete { get; set; }
        public Nullable<decimal> masa_a_siete { get; set; }
        public Nullable<decimal> altura_aa_siete { get; set; }
        public Nullable<decimal> altura_ab_siete { get; set; }
        public Nullable<decimal> lados_aa_siete { get; set; }
        public Nullable<decimal> lados_ab_siete { get; set; }
        public string directo_a_siete { get; set; }
        public string intensidad_a_siete { get; set; }
        public Nullable<decimal> presion_a_siete { get; set; }
        public string tipofalla_a_siete { get; set; }
        public Nullable<int> clave_ensa_b_siete { get; set; }
        public Nullable<decimal> masa_b_siete { get; set; }
        public Nullable<decimal> altura_ba_siete { get; set; }
        public Nullable<decimal> altura_bb_siete { get; set; }
        public Nullable<decimal> lados_ba_siete { get; set; }
        public Nullable<decimal> lados_bb_siete { get; set; }
        public string directo_b_siete { get; set; }
        public string intensidad_b_siete { get; set; }
        public Nullable<decimal> presion_b_siete { get; set; }
        public string tipofalla_b_siete { get; set; }
        public Nullable<int> clave_ensa_a_catorce { get; set; }
        public Nullable<decimal> masa_a_catorce { get; set; }
        public Nullable<decimal> altura_aa_catorce { get; set; }
        public Nullable<decimal> altura_ab_catorce { get; set; }
        public Nullable<decimal> lados_aa_catorce { get; set; }
        public Nullable<decimal> lados_ab_catorce { get; set; }
        public string directo_a_catorce { get; set; }
        public string intensidad_a_catorce { get; set; }
        public Nullable<decimal> presion_a_catorce { get; set; }
        public string tipofalla_a_catorce { get; set; }
        public Nullable<int> clave_ensa_b_catorce { get; set; }
        public Nullable<decimal> masa_b_catorce { get; set; }
        public Nullable<decimal> altura_ba_catorce { get; set; }
        public Nullable<decimal> altura_bb_catorce { get; set; }
        public Nullable<decimal> lados_ba_catorce { get; set; }
        public Nullable<decimal> lados_bb_catorce { get; set; }
        public string directo_b_catorce { get; set; }
        public string intensidad_b_catorce { get; set; }
        public Nullable<decimal> presion_b_catorce { get; set; }
        public string tipofalla_b_catorce { get; set; }
        public Nullable<int> clave_ensa_a_veiteocho { get; set; }
        public Nullable<decimal> masa_a_veiteocho { get; set; }
        public Nullable<decimal> altura_aa_veiteocho { get; set; }
        public Nullable<decimal> altura_ab_veiteocho { get; set; }
        public Nullable<decimal> lados_aa_veiteocho { get; set; }
        public Nullable<decimal> lados_ab_veiteocho { get; set; }
        public string directo_a_veiteocho { get; set; }
        public string intensidad_a_veiteocho { get; set; }
        public Nullable<decimal> presion_a_veiteocho { get; set; }
        public string tipofalla_a_veiteocho { get; set; }
        public Nullable<int> clave_ensa_b_veiteocho { get; set; }
        public Nullable<decimal> masa_b_veiteocho { get; set; }
        public Nullable<decimal> altura_ba_veiteocho { get; set; }
        public Nullable<decimal> altura_bb_veiteocho { get; set; }
        public Nullable<decimal> lados_ba_veiteocho { get; set; }
        public Nullable<decimal> lados_bb_veiteocho { get; set; }
        public string directo_b_veiteocho { get; set; }
        public string intensidad_b_veiteocho { get; set; }
        public Nullable<decimal> presion_b_veiteocho { get; set; }
        public string tipofalla_b_veiteocho { get; set; }
        public Nullable<int> clave_ensa_a_n { get; set; }
        public Nullable<decimal> masa_a_n { get; set; }
        public Nullable<decimal> altura_aa_n { get; set; }
        public Nullable<decimal> altura_ab_n { get; set; }
        public Nullable<decimal> lados_aa_n { get; set; }
        public Nullable<decimal> lados_ab_n { get; set; }
        public string directo_a_n { get; set; }
        public string intensidad_a_n { get; set; }
        public Nullable<decimal> presion_a_n { get; set; }
        public string tipofalla_a_n { get; set; }
        public Nullable<int> clave_ensa_b_n { get; set; }
        public Nullable<decimal> masa_b_n { get; set; }
        public Nullable<decimal> altura_ba_n { get; set; }
        public Nullable<decimal> altura_bb_n { get; set; }
        public Nullable<decimal> lados_ba_n { get; set; }
        public Nullable<decimal> lados_bb_n { get; set; }
        public string directo_b_n { get; set; }
        public string intensidad_b_n { get; set; }
        public Nullable<decimal> presion_b_n { get; set; }
        public string tipofalla_b_n { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid concreto_rpc_ID { get; set; }
    
        public virtual fact_ensaye_esp_est fact_ensaye_esp_est { get; set; }
        public virtual inf_rpc inf_rpc { get; set; }
    }
}
