//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_prospectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_prospectos()
        {
            this.inf_prosp_cont = new HashSet<inf_prosp_cont>();
        }
    
        public System.Guid prospecto_ID { get; set; }
        public int prosp_giro_ID { get; set; }
        public int prosp_tserv_ID { get; set; }
        public Nullable<int> prosp_est_ID { get; set; }
        public string cod_prospecto { get; set; }
        public int prosp_tipocont_ID { get; set; }
        public string empresa { get; set; }
        public string web { get; set; }
        public string callenum { get; set; }
        public string d_codigo { get; set; }
        public Nullable<int> id_asenta_cpcons { get; set; }
        public Nullable<System.DateTime> registro { get; set; }
        public System.Guid empresa_ID { get; set; }
        public System.Guid usuario_ID { get; set; }
    
        public virtual fact_prosp_est fact_prosp_est { get; set; }
        public virtual fact_prosp_giro fact_prosp_giro { get; set; }
        public virtual fact_prosp_tcont fact_prosp_tcont { get; set; }
        public virtual fact_prosp_tserv fact_prosp_tserv { get; set; }
        public virtual inf_emp inf_emp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_prosp_cont> inf_prosp_cont { get; set; }
    }
}
